spring:
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     #view-names: thymeleaf/*    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.danbplus.com:53306/danbplusSTS_CYO?UTC&allowPublickeyRetrieval=true
    username: danbplus
    password: Danb1235!!
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: cyo
server:
  port: '8000'