spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.danbplus.com:53306/danbplusSTS_CYO?UTC&allowPublickeyRetrieval=true
    username: danbplus
    password: Danb1235!!
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: cyo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: '8000'